### ISSUE TITLE
iLED 1st Stage: Disaggregate VLC LEDS n Other Appliances

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/hilo-disaggregator#4]
> We believe that Fourier transforms and filters can help us disaggregate light consumption from other electrical loads (so our framework can still be applied)

FFT and filters to separate 50Hz loads (other appliances) and  1-10kHz load (VLC LEDs)

**Comment by bontorhumala** [comment]
1. In matlab, create 50Hz random signal and 1/10kHz random signal. Combine. Try to disaggregate

**Comment by akshay-sn** [comment]
Disaggregating light energy consumption in presence of other appliances:
In previous sections, we described the performance of iLED when all the lights are connected to a single energy meter. In this section, we shed light on how to identify the LEDs which are ON/OFF when an energy meter measures consumption of lights along with other appliances like HVAC, washing machines, electric fans, refrigerators, etc. Our hypothesis is that since most of the appliances use either 50 Hz or 60 Hz signal, a band-pass filter at the energy meter side would be able to distinguish signals from appliances (50Hz) and LEDs modulating at high frequencies (e.g. 10kHz). A band- pass filter passes frequencies within a certain range. Thus we design a band-pass filter to decompose 50Hz signal from the aggregated signal. The sampling frequency was considered o be 44.1kHz which is supported by commercial energy meters [?]. The 50Hz signal is then passed to one of the existing energy disaggregation algorithms such as Combina- torial optimization [?] or Factorial Hidden Markov Models (FHMM) [?] to obtain appliance level energy consumption. The high frequency decomposed signal (corresponding to the modulated signal from LEDs) are then given as input to the proposed iLED framework.

All evaluation results were shown till now considered LEDs either being turned ON/OFF. However, there might be LEDs which are dimmable, i.e. the power consumption of the LED can be reduced further. In the proposed approach all LEDs are modulating at a constant frequency and hence to decode the superposition of signals from multiple dimmable lights is challenging. The previous idea can also be used when there are dimming LEDs in the building. In this case, each dimming level will modulate at a different frequency and a band-pass filter will be able to decompose the signals based on different frequencies. For example, a LED with dim level-1 can modulate at 10kHz and dim level-2 can modulate at 5kHz and so on. The aggregated received signal is then decomposed with the help of band-pass filter for each center frequency. Fig. 14 shows the signals for appliances (50Hz), modulating signals from LEDs with different frequencies (10kHz, 5kHz, 3kHz, 2kHz, and 1kHz), the aggregated received signal at the energy meter. The received signal is then decomposed with a band-pass filter and the reconstructed signals along with the original signal is shown in Fig. 14.
[dimming.pdf](https://github.com/bontorhumala/hilo-disaggregator/files/845663/dimming.pdf)

**Comment by bontorhumala** [comment]
See https://github.com/bontorhumala/hilo-disaggregator/issues/12
